# Generated by Django 3.2 on 2023-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=50, unique=True, verbose_name='codename'),
        ),
    ]
