# Generated by Django 3.2 on 2023-09-05 13:19

from django.db import migrations, models
import user_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a valid phone number.', max_length=11, validators=[user_management.validators.validate_phone_number], verbose_name='phone number'),
        ),
    ]
