# Generated by Django 3.2 on 2023-09-05 13:44

from django.db import migrations, models
import user_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[user_management.validators.validate_phone_number], verbose_name='phone number'),
        ),
    ]
