# Generated by Django 3.2 on 2023-09-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20230905_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='employee_pictures/default.jpg', upload_to='employee_pictures', verbose_name='picture'),
        ),
    ]
