# Generated by Django 3.2 on 2023-09-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='employee_default_pic.jpg', upload_to='employee_pictures', verbose_name='picture'),
        ),
    ]
