# Generated by Django 3.2 on 2023-09-10 04:25

from django.db import migrations, models
import user_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20230910_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[user_management.validators.validate_birth_date], verbose_name='birth date'),
        ),
    ]
