# Generated by Django 3.2 on 2023-09-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
