# Generated by Django 3.2 on 2023-09-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_taskfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
